version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: school-diary-db
    environment:
      POSTGRES_USER: school_user
      POSTGRES_PASSWORD: school_pass
      POSTGRES_DB: schooldiary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: